# Generated by Django 5.2.14 on 2026-06-03 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_recipie_6e3964_idx',
            old_name='notificatio_recipie_idx',
        ),
    ]
