# Generated by Django 5.0.14 on 2026-05-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_friendship'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='friendship',
            name='unique_friendship',
        ),
        migrations.RenameIndex(
            model_name='friendship',
            new_name='friendships_from_us_a47fdf_idx',
            old_name='friendships_from_user_status_idx',
        ),
        migrations.RenameIndex(
            model_name='friendship',
            new_name='friendships_to_user_607283_idx',
            old_name='friendships_to_user_status_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='users_is_admi_d35647_idx',
            old_name='users_is_admi_39000a_idx',
        ),
        migrations.AlterField(
            model_name='adminauditevent',
            name='action',
            field=models.CharField(choices=[('create_user', 'Create User'), ('register_user', 'Register User'), ('email_verify_sent', 'Email Verify Sent'), ('email_verified', 'Email Verified'), ('password_reset_sent', 'Password Reset Sent'), ('password_reset_confirmed', 'Password Reset Confirmed'), ('activate', 'Activate'), ('deactivate', 'Deactivate'), ('ban', 'Ban'), ('unban', 'Unban'), ('reset_password', 'Reset Password'), ('change_groups', 'Change Groups'), ('update_user', 'Update User'), ('unity_token_issued', 'Unity Token Issued'), ('admin_verified', 'Admin Verified'), ('admin_unverified', 'Admin Unverified')], db_index=True, max_length=32),
        ),
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together={('from_user', 'to_user')},
        ),
    ]
