# Generated by Django 5.2.14 on 2026-05-25 17:46

from django.db import migrations


def rename_players_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name='players').update(name='members')
    Permission = apps.get_model('auth', 'Permission')
    Permission.objects.filter(codename__in=['can_play', 'can_trade']).delete()


def reverse_rename(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name='members').update(name='players')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_add_bio_website_to_user'),
    ]

    operations = [
        migrations.RunPython(rename_players_group, reverse_code=reverse_rename),
    ]
