# Generated by Django 5.2.14 on 2026-05-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_rename_players_to_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hwid',
        ),
        migrations.AlterField(
            model_name='adminauditevent',
            name='action',
            field=models.CharField(choices=[('create_user', 'Create User'), ('register_user', 'Register User'), ('email_verify_sent', 'Email Verify Sent'), ('email_verified', 'Email Verified'), ('password_reset_sent', 'Password Reset Sent'), ('password_reset_confirmed', 'Password Reset Confirmed'), ('activate', 'Activate'), ('deactivate', 'Deactivate'), ('ban', 'Ban'), ('unban', 'Unban'), ('reset_password', 'Reset Password'), ('change_groups', 'Change Groups'), ('update_user', 'Update User'), ('admin_verified', 'Admin Verified'), ('admin_unverified', 'Admin Unverified')], db_index=True, max_length=32),
        ),
    ]
