# Generated by Django 5.2.14 on 2026-06-03 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_backupjob_stage_cancel'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='backupjob',
            new_name='accounts_ba_kind_9cdf53_idx',
            old_name='accounts_ba_kind_1f3f4c_idx',
        ),
        migrations.RenameIndex(
            model_name='backupjob',
            new_name='accounts_ba_status_34b494_idx',
            old_name='accounts_ba_status_0f3f75_idx',
        ),
        migrations.RenameIndex(
            model_name='backupjob',
            new_name='accounts_ba_backup__b3ffc0_idx',
            old_name='accounts_ba_backup__8ad2ef_idx',
        ),
        migrations.RenameIndex(
            model_name='backupjob',
            new_name='accounts_ba_stage_6388b3_idx',
            old_name='accounts_ba_stage__6c15f2_idx',
        ),
        migrations.AlterField(
            model_name='adminauditevent',
            name='action',
            field=models.CharField(choices=[('create_user', 'Create User'), ('register_user', 'Register User'), ('email_verify_sent', 'Email Verify Sent'), ('email_verified', 'Email Verified'), ('password_reset_sent', 'Password Reset Sent'), ('password_reset_confirmed', 'Password Reset Confirmed'), ('activate', 'Activate'), ('deactivate', 'Deactivate'), ('ban', 'Ban'), ('unban', 'Unban'), ('reset_password', 'Reset Password'), ('change_groups', 'Change Groups'), ('update_user', 'Update User'), ('admin_verified', 'Admin Verified'), ('admin_unverified', 'Admin Unverified'), ('backup_create', 'Backup Create'), ('backup_delete', 'Backup Delete'), ('backup_prune', 'Backup Prune'), ('backup_prune_job', 'Backup Prune Job'), ('backup_restore', 'Backup Restore'), ('backup_restore_job', 'Backup Restore Job'), ('backup_backup_job', 'Backup Backup Job'), ('backup_job_cancel', 'Backup Job Cancel')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='backupjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=16),
        ),
    ]
