# Generated by Django 5.2.14 on 2026-05-22 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_import_from_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='image',
            field=models.ImageField(upload_to='uploads'),
        ),
    ]
