# Generated by Django 5.2.14 on 2026-05-22 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_topic_category_index'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='topic',
            new_name='forum_topic_categor_8ac930_idx',
            old_name='forum_topic_cat_pin_reply_idx',
        ),
    ]
